dist: trusty
sudo: false
language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3
  - ruby-head
before_install:
  - gem install bundler -v 2.0.1
  - bundle update
  - unset _JAVA_OPTIONS
matrix:
  allow_failures:
    - rvm: ruby-head
jobs:
  include:
    - stage: Update project site
      script: >
        echo "TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST" &&
        if [[ ($TRAVIS_BRANCH == master) &&
              ($TRAVIS_PULL_REQUEST == false) ]] ; then
          curl -LO --retry 3 https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh &&
          sh trigger-travis.sh --pro riboseinc metanorma.com $TRAVIS_ACCESS_TOKEN;
        fi
